name: Mantenha os aplicativos Streamlit ativos

on:
  schedule:
    - cron: "17 */3 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping dashboards
        run: |
          wget --spider --timeout=60 --tries=2 --user-agent="Mozilla/5.0" https://agrobasis-usda.streamlit.app/
          wget --spider --timeout=60 --tries=2 --user-agent="Mozilla/5.0" https://agrobasis-usda-milho.streamlit.app/
          wget --spider --timeout=60 --tries=2 --user-agent="Mozilla/5.0" https://spread-milho.streamlit.app/
          wget --spider --timeout=60 --tries=2 --user-agent="Mozilla/5.0" https://usda-trigo.streamlit.app/
          wget --spider --timeout=60 --tries=2 --user-agent="Mozilla/5.0" https://agrobasis-basis-milho.streamlit.app/
